remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Ramblings of a software engineer
description: A memory aid to help me remember what I would otherwise forget...
